### ISSUE TITLE
Mysterious filesystem errors

### ISSUE THREAD

**Issue by sebbacon** [opensafely/job-runner#31]
Utterly baffling filesystem-related errors on the analysis server. Specifically, it affects filesystems which are mounted in the `docker run --volume src:dst` form. Files and folders which are created in dst fail to persist; 

* mounted files and folders are "disappearing" after a docker container has finished [link]()
* while a container is running, `ls -l` showing a readable file but `cat <file>` giving `No such file or directory`
* a directory that has been renamed showing up in ls under its old name but being accessible (via cd) under both its old and new names.
 * files that appear in ls, initially throw No such file when you cat them the first time, but then read OK when you cat them the second time. 
* `git init` operations failing because the folder they're being run in has disappeared

To reproduce, this makes a directory; mounts the parent in Docker and runs ls to confirm it was there; renames the directory on the host; re-runs docker and it is still there under the old name. Confirmed that this does not fail on local machine. Commands:

```sh
mkdir test1
docker run --rm -v "/$PWD:/workspace" --entrypoint bash docker.opensafely.org/cohortextractor -c ls
mv test1 test2
docker run --rm -v "/$PWD:/workspace" --entrypoint bash docker.opensafely.org/cohortextractor -c ls
```

There is some ambiguity on the server as to which version of docker is being run:

```sh
$ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false
Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

versus:

```
$ which docker
/c/Program Files/Docker/Docker/resources/bin/docker
$ cd /c/Program\ Files/Docker/Docker
$ grep -i version installationmanifest.json
      "dir": "version-bin",
  "humanVersion": "2.2.0.4",
      "errorMessage": "Docker Desktop requires Windows 10 Pro or Enterprise version 15063 to run.",
      "kind": "osversion"
  "version": "43472"
```

**Comment by sebbacon** [comment]
Research about possible bugs:

[This ticket](https://github.com/docker/for-win/issues/5530) describes changes on the host not being reflected in the mounted container volume. Some comments on that ticket also mention the inverse being the case. It is a regression that appears in 2.2 and [is claimed]() to be fixed in 2.3.0.1, though comments in the same thread suggest otherwise, for some people at least. 

That ticket is locked but other tickets have been opened which suggest the problem persists, also in WSL2; [this comment](https://github.com/docker/for-win/issues/7276#issuecomment-661965618) is worth quoting in full

>>    After doing some more digging, it looks like it may not be a problem caused by docker, but by WSL2.
>
>I had this problem without WSL enabled (Hyper-V enabled instead). Was using Docker 2.3.0.3. I actually jumped through all the hoops to upgrade Windows 10 to the 2004 version so that I could install WSL2 hoping that it would fix this issue (it didn't of course).
>
>Looks like Windows bind mounts were broken while refactoring code the last few releases (probably in anticipation of WSL 2) as seen here [#5530](https://github.com/docker/for-win/issues/5530)
>
>>    See: [#5888](https://github.com/docker/for-win/issues/5888)

> That issue is closed now. Looks like automated close bot got it...
>
>So it looks like the workarounds are (ordered with increasing horribleness):
>
>    rollback to Docker [2.1.0.5](https://download.docker.com/win/stable/40693/Docker%20Desktop%20Installer.exe)
 >   docker-compose restart after each file change
>    put your code inside a WSL VM and then launch docker from within the VM and edit your files from within the VM (and you can use a hack like a VSCode plugin to edit files inside the VM from outside)

My tentative conclusion is that Docker for Windows is a complete mess, much worse than we expected, and that we should accelerate conversations about installing Ubuntu/Debian within a VM on the Windows Server, if at all possible.

In the mean time, rolling back to 2.1.0.5 would seem a sensible interim step.

**Comment by evansd** [comment]
The version ambiguity is now resolved: Docker Desktop for Windows is a sort of meta-package that bundles up a bunch of different components and is versioned separately. So e..g Docker Desktop v2.3.0.5 contains Docker Engine v19.03.12 and Docker Compose v1.26.2.

Compare:
https://docs.docker.com/docker-for-windows/release-notes/
https://docs.docker.com/engine/release-notes/

**Comment by evansd** [comment]
Restarting Docker seems to have restored normal behaviour for now.

We've been speculating that the bug only recently surfaced because the job runner was stressing the filesystem while running the large number of "snotty noses" jobs. We have [plans](https://github.com/opensafely/job-runner/issues/32) to reduce the fs activity of the job runner, but this is obviously more of a sticking plaster than a long-term solution.

**Comment by evansd** [comment]
The issue has resurfaced, although not to the extent that I can reliably reproduce as I could before and so far it seems to be only affecting Will's vacc-trial repo. I've added a basic [integrity check](https://github.com/opensafely/server-instructions/pull/11) to the cohortextractor wrapper script so at least we shouldn't end up accidentally running with the wrong version of study definitions.

**Comment by sebbacon** [comment]
Downgrade happened on 29 Sept 2020:

![image](https://user-images.githubusercontent.com/211271/95080083-73954b80-070f-11eb-9c50-8dabf567e17c.png)
