### ISSUE TITLE
Run as a service

### ISSUE THREAD

**Issue by bloodearnest** [opensafely/job-runner#33]
We need job-runner to run as a proper service, managed and restarted by the host system

Currently, this probably needs to a be a Windows service that starts up a job-runner process. Given that this means that updates to this windows service would need to go through TPP's admin access (and possibly packaged as msi or similar), we should probably try to minimise the need for this, and have the actual windows service simply babysit a separate process that we can update/interact with without admin access. This should hopefully allow us to update the job-runner code ourselves via git rather than having to involve TPP.

Hopefully, we'll move towards managing our own VM, which means this could run a systemd unit instead, and not need to interact with the host at all. Not a priority, but something to bear in mind.

**Comment by evansd** [comment]
It seems it's possible to tell Docker that certain containers should be always run, and restarted if they fail:
https://docs.docker.com/config/containers/start-containers-automatically/

I obviously don't fully trust this, and ideally we'd be able to manage this all within our own VM, but it might be a good place to start given that we don't need to involve anyone else.

**Comment by bloodearnest** [comment]
Hah, I just saw that myself, yes, much better if it works. To deploy, we could publish a job-runner docker image, pull, restart.
Or docker build locally from a git repo, if we have the base layers available.

**Comment by sebbacon** [comment]
Just to throw in we also want to work out storing/shipping logs between container restarts.

> I obviously don't fully trust this

I've taken a look previously at the restart functionality and had a short play and decided I wasn't confident I understood fully what it was meant to do, or if it did what it was meant to do, but then I was in a hurry :)
