### ISSUE TITLE
Problems in dependency-running via job server

### ISSUE THREAD

**Issue by sebbacon** [opensafely/job-runner#34]
In a recent "full run" of https://github.com/opensafely/school-age-children-and-covid, there were a number of unexpected issues. This ticket is to track them.

* [x] A number of the cox models failed because expected outputs were not there. For example, `10_an_interaction_cox_models_shield_non_covid_death` (job 75) didn't have files matching `output/an_interaction_cox_models_non_covid_death_week*_ageband_*.ster`, and `07d_an_multivariable_cox_models_FULL_Sense5_covid_tpp_prob` didn't have files matching `output/an_sense_covid_tpp_prob_*_ageband_*.ster` (job 63)
* [x] Some had "unclassified errors", e.g. `06_univariate_analysis_covid_death` (job 57) and `07b_an_multivariable_cox_models_FULL_covid_icu` (job 41)
* [x] Some never finished, e.g. `10_an_interaction_cox_models_weeks_covid_icu` (job 31) and `08_an_tablecontent_HRtable_covid_death` (job 59)

**Comment by sebbacon** [comment]
Have retriggered a few of the failed jobs (having lost the logs due to a restart... sigh)

```
07d_an_multivariable_cox_models_FULL_Sense5_covidadmission
10_an_interaction_cox_models_time_covid_icu
10_an_interaction_cox_models_shield_covid_icu
07d_an_multivariable_cox_models_FULL_Sense5_covid_icu
10_an_interaction_cox_models_weeks_covid_death
10_an_interaction_cox_models_time_covid_death
06_univariate_analysis_covid_death
```

The last was previously an unclassified error, and the others had missing `output` files.

Have manually verified (again) that one of the actions that lacked output files does produce them locally, with

    cohortextractor --verbose run dummy 07d_an_multivariable_cox_models_FULL_Sense5_covidadmission expectations

Hard to come up with a reason why these might not exist. From code-reading it would simply be because they weren't created; but this is "impossible" because the same script, with different parameters, ran successfully around the same time.

We could still be seeing disappearing files per #31, as these are files that are created by a docker container on a mount.

**Comment by sebbacon** [comment]
`06_univariate_analysis_covid_death` (unclassified error) has just completed successfully. This isn't too surprising as "unclassified" usually means something like "docker container was killed unexpectedly".

**Comment by sebbacon** [comment]
At 11:36UTC,  `10_an_interaction_cox_models_shield_covid_icu` failed after about 4 hours run time. It created a log file which was copied to the `high_privacy` volume, but the expected `*.ster` file(s) was not found in `output/*.ster`

However, at 11:48 `07d_an_multivariable_cox_models_FULL_Sense5_covid_icu` did complete successfully and copied output from `output/*.ster`.

**Comment by sebbacon** [comment]
Have popped failed jobs back on the queue at least twice over the weekend to see if they eventually run, but am on holiday, so in grabbed moments...

Most recently (`2020-10-03T12:54`) I added these jobs, which all subsequently failed *except one* (`07d_an_multivariable_cox_models_FULL_Sense5_covid_death`):

```
02_an_data_checks 
07d_an_multivariable_cox_models_FULL_Sense5_covid_death 
10_an_interaction_cox_models_shield_covid_death 
10_an_interaction_cox_models_shield_covid_icu 
10_an_interaction_cox_models_shield_covid_tpp_prob 
10_an_interaction_cox_models_shield_covidadmission 
10_an_interaction_cox_models_shield_non_covid_death 
10_an_interaction_cox_models_time_covid_death 
10_an_interaction_cox_models_time_covid_tpp_prob 
10_an_interaction_cox_models_time_covidadmission 
10_an_interaction_cox_models_time_non_covid_death
10_an_interaction_cox_models_weeks_covidadmission 
```

`07d_an_multivariable_cox_models_FULL_Sense5_covid_death`, the one which worked, had previously failed with the usual `output/an_sense_covid_death_*_ageband_*.ster` error. As this has all happened over the weekend when nothing else is happening, this is a pretty clear example of a nondeterministic error. 

Over the weekend, for the first time, we also saw the disappearance of a log file, rather than a ster file, viz `log/10_an_interaction_cox_models_weeks_covidadmission.log`

It is notable that nearly all these disappearing outputs are related to cox models. The 5 `weeks` versions (i.e. all actions matching `10_an_interaction_cox_models_weeks*`) produced outputs successfully all but once.  By contrast, all the other cox models appear to have failed.  One thing all the failed jobs _appear_ to have in common is a longer run time (3h+).

There are also two jobs claimed to be still running since 2020/10/002 07:19, i.e. over 48 hours ago:

```
10_an_interaction_cox_models_time_covid_icu
10_an_interaction_cox_models_weeks_covid_death
```

**Comment by sebbacon** [comment]
Have just kicked off the following again before I go out for the day:

```
02_an_data_checks
10_an_interaction_cox_models_shield_covid_death
10_an_interaction_cox_models_shield_covid_icu
10_an_interaction_cox_models_shield_covid_tpp_prob
10_an_interaction_cox_models_shield_covidadmission
10_an_interaction_cox_models_shield_non_covid_death
10_an_interaction_cox_models_time_covid_death
10_an_interaction_cox_models_time_covid_tpp_prob
10_an_interaction_cox_models_time_covidadmission
10_an_interaction_cox_models_time_non_covid_death
10_an_interaction_cox_models_weeks_covidadmission
```

**Comment by sebbacon** [comment]
Am now focussing on `10_an_interaction_cox_models_shield_non_covid_death`.

On the last failed run, it failed because there was no output at `output/an_interaction_cox_models_non_covid_death_week*_ageband_*.ster`

Looking at the log file that *did* get generated, it says it created a file at `output/an_interaction_cox_models_non_covid_death_kids_cat3_shield_MAINFULLYADJMODEL_agespline_bmicat_noeth_ageband_1.ster`

Here is the `project.yaml` action:

![image](https://user-images.githubusercontent.com/211271/95071733-0c24cf00-0702-11eb-9695-d50d862abaee.png)

Here's [the line](https://github.com/opensafely/school-age-children-and-covid/blob/a7afa06c681ac096cbbf4c8834dac4baf9485c30/analysis/10_an_interaction_cox_models_time.do#L117) where it's saved:

![image](https://user-images.githubusercontent.com/211271/95071871-3ecec780-0702-11eb-8215-eead6841d81d.png)

So it actually just looks like the outputs are wrong

**Comment by sebbacon** [comment]
Similar problem with log outputs; the special-cased `10_an_interaction_cox_models_weeks_covidadmission` action expects logging to `log/10_an_interaction_cox_models_weeks_covidadmission.log`,but that script actually logs using `log/10a_an_interaction_cox_models_weeks_covidad`

**Comment by evansd** [comment]
Ah, and plausibly the reason none of these issues showed up locally is that everything runs in place, so the job-runner was picking up files created by earlier jobs which happened to match.

**Comment by evansd** [comment]
We could make it check the timestamps or something like that when running locally i.e. make sure this file was created _after_ the job started running.

**Comment by sebbacon** [comment]
Exactly! Was going to think about a fix for this next up

**Comment by sebbacon** [comment]
`01_an_data_checks` is failing because 

```
use $tempdir/analysis_dataset, clearn
file tempdata/analys_dataset.dta not found
```
See https://github.com/opensafely/school-age-children-and-covid/pull/58
