### ISSUE TITLE
Docker on Windows CPU utilisation

### ISSUE THREAD

**Issue by sebbacon** [opensafely/job-runner#35]
On a long-running stata process (> 12 hours), I can see from within a linux container (using `top`) that 4 CPUs are running at 100%.

On a different long-running python process, I can see exactly the same CPUs maxing out.

Using `vmstat` I see this all the CPU activity is happening in user time.

When I look at task manager on the Windows host, I can't see any CPU running over 65% (approx, average, I only get to see the little charts), with some spiking to 90%.

I don't understand this behaviour, and would quite like to, seeing as the processes as CPU-bound and taking forever.

The answer might remain "meh, Docker Desktop on Windows", of course.

**Comment by sebbacon** [comment]
To access the container in question, I run `docker exec -it tpp-https-github-com-opensafely-school-age-children-and-covid-master-full-school-age-children-10-an-interaction-cox-models-weeks-non-covid-death /bin/bash`

**Comment by sebbacon** [comment]
Update: one of the 4 containers has finished successfully (running stata, `10_an_interaction_cox_models_weeks_covid_tpp_prob`), and now there are 3 at 100%.

**Comment by bloodearnest** [comment]
Ah, right. IIRC, docker doesn't have the nice convenience of lxcfs, so the resources visible in the container are the same as the host by default? Hence the 4 dockers, 4 cpus pegged? I was thinking the one docker instance was using 4 cpus #dockern00b

**Comment by sebbacon** [comment]
Right. So I don't think this is a mystery after all. The 4 docker containers running were 3x cox regressions in stata, which we've established can only use one core ([slack thread](https://ebmdatalab.slack.com/archives/C63UXGB8E/p1601574337364100), [stata docs](https://www.stata.com/statamp/statamp-20171003.pdf)), and a jupyter notebook running python, which will almost certainly only be using one core also.

So I don't think there's a contention issue and everything is running as expected.  These are just slow scripts and speedup would have to be obtained through better parallelisation.
