### ISSUE TITLE
Main loop freezes after HTTP errors

### ISSUE THREAD

**Issue by sebbacon** [opensafely/job-runner#40]
The main loop catches HTTP errors, sleeps for 30 seconds, and continues.

There were 500 errors during a job server restart. Twice the errors were caught, and a sleep happened; but the third time, although the `sleep` was logged, no further activity took place.

Here is the full set of tracebacks that the logs ended with:

https://gist.github.com/sebbacon/1ed063813e8b848096803e61132b23aa

This is similar enough to #36 for me to close that one, but note ctrl+C had an odd effect there, which it didn't this time.

**Comment by bloodearnest** [comment]
Similar hangup occurred ~9am 27/10/2020. Process not responsive to signals. Errors in the logs include some git based GnuTLS errors, and complaining about not finding a file (data/mosa_shp.rds) in this case.

**Comment by sebbacon** [comment]
One hypothesis about hangups is addressed in https://github.com/opensafely/job-runner/commit/1be8e5341cd9aced3314cd28ea56aa29a0ee976f
