### ISSUE TITLE
I/O issues when copying/using large input files

### ISSUE THREAD

**Issue by sebbacon** [opensafely/job-runner#41]
When running several actions in parallel on the production (Windows) server, things grind to a halt.

Just running `ls` inside a container is extremely slow.

This was observed when several docker containers had been started at once.  The hypothesis was that the step where files are copied from the relevant storage into the container was hitting some kind of IO limit. 

As an attempted fix, https://github.com/opensafely/job-runner/pull/38/commits/10bd9ffcd6794c0d37f8d8418d59e34b46c04bcd caused individual input files to be mounted read-only, rather than copied.

However, similar behaviour was observed following the change.

As ever, it's hard to understand the implementation of volume / bind mounting in Docker, but my sense is that a bind mount still results in a copy operation before the `RUN` command is executed, thus making the change above a bit pointless.

The documentation is unclear, but I believe we currently use bind mounts rather volumes; that is, I think `--volume /path:/dst` is a bind mount from the `/path` location on the host filesystem, but `--volume path:/dst` is a volume mount from the `path` volume on the host filesystem.

The Docker documentation says that "a volume’s contents exist outside the lifecycle of a given container", which implies that perhaps creating a volume and mounting that will involve less IO.

The process would be 

1. Before running a docker container, at the point input files are copied in, use some kind of hashed key to see if a volume has already been created for those input files
2. If not, create a volume and copy the input files in (as far as I can tell, this must be done by creating a docker container with a new volume mounted)
3. Then mount the volume

Before implementing this, it's worth creating a test case to check assumptions about IO.  This would involve:

```
fallocate -l 3G very_large_file.txt

for i in {1..5}; do
  docker run -d --rm --entrypoint bash --volume $(pwd)/very_large_file.txt:/tmp/very_large_file.txt:ro docker.opensafely.org/job-runner -c sleep 600s
done;

docker run --rm --entrypoint bash  -it --volume $(pwd)/very_large_file.txt:/tmp/very_large_file.txt:ro docker.opensafely.org/job-runner -c "ls -l /tmp/very_large_file.txt"


```

**Comment by evansd** [comment]
Beware that if you're doing this in git-bash you need an extra leading slash on the host path (so `/$(pwd)` rather than `$(pwd)`) for it to work as expected.

**Comment by sebbacon** [comment]
So the above test case does not create lots of IO. Next step: same thing but reading the mounted files in each docker

```

for i in {1..5}; do
  docker run -d --rm --entrypoint bash --volume $(pwd)/very_large_file.txt:/tmp/very_large_file.txt:ro docker.opensafely.org/job-runner -c "dd if=/tmp/very_large_file.txt of=/dev/zero"
done;
docker run --rm --entrypoint bash  -it --volume $(pwd)/very_large_file.txt:/tmp/very_large_file.txt:ro docker.opensafely.org/job-runner -c "dd if=/tmp/very_large_file.txt of=/dev/zero"

```

**Comment by sebbacon** [comment]
...and that makes everything very slow.

**Comment by sebbacon** [comment]
On my laptop:

```
$ fallocate -l 3.9G very_large_file.txt
$ docker run  --rm --entrypoint bash  -it --volume $(pwd)/very_large_file.txt:/tmp/very_large_file.txt:ro docker.opensafely.org/job-runner -c "dd if=/tmp/very_large_file.txt of=/dev/null"
8388608+0 records in
8388608+0 records out
4294967296 bytes (4.3 GB, 4.0 GiB) copied, 12.9653 s, 331 MB/s
```
Same thing on TPP:

**Comment by sebbacon** [comment]
Test script for doing the same as above but with volumes:

```sh
docker container create --name dummy -v myvolume:/root docker.opensafely.org/job-runner
docker cp very_large_file.txt dummy:/tmp/very_large_file.txt
docker rm dummy

docker run  --rm --entrypoint bash  -it --volume myvolume:/tmp/:ro docker.opensafely.org/job-runner -c "dd if=/tmp/very_large_file.txt of=/dev/null"
```
