### ISSUE TITLE
Running job-runner inside docker might be the cause of our IO issues

### ISSUE THREAD

**Issue by bloodearnest** [opensafely/job-runner#59]
In fixing #41, we did some tests (which I've confirmed worked for me too) and IO to docker volumes was much quicker that filesharing, so #56 switched to using those inside job-runner, adding a pre-run step of copying the data into a volume before running the job.

However, slowness persisted, and was actually exaggerated by this change, as we copied data that wasn't actually needed by the action (dependencies are not file level granularity)

I think this is because we run job-runner *inside docker*, with the /e/high_privacy path that it accesses being shared over slow file mount.  So when job-runner runs a `docker cp` from inside its container, the fileshared source in /e/high_privacy is being used, so things are still slow.

I've tested this manually by repeating the test from #41 inside a docker container with the same file shares as job-runner, and the docker cp is slow as expected.

To gain the speed up using volumes, we would need to run job-runner outside of docker, on the windows host itself.

I'm gonna take a quick spike to see how hard/easy that would be.

**Comment by sebbacon** [comment]
So regarding docker-within-docker, the *theory* is that this code means everything is happening in the context of the Windows host:

https://github.com/opensafely/job-runner/blob/3e7806eb07a7fa9c587db1bb014f713827241a20/docker-compose.yaml#L37-L39

Not sure if that actually helps here or not -- just dropped by to say that...

**Comment by bloodearnest** [comment]
I suspect the path resolution from mount cli args is done client side, though, so inside the docker container. I don't see how it could be any other way, tbh. I think we've possibly confused ourselves by mounting hosts /e/high_privacy at /e/high_privacy in the container, but they are not the same thing.

Two bits of evidence for my theory:

- copying into a volume from the host with `docker cp very_large_file.txt volume:/tmp/file.txt` is fast. Running the same docker cp command from inside a docker container that was run with `-v /e/high_privacy:/e/high_privacy` is slow. This is not becuase the volume write is slow, but because the fileshare read is slow.

- It explains why your change worked in test but not in prod.

We don't have python or anything to easily try run job-runner on the host to test.

**Comment by evansd** [comment]
Can we ship a pyoxidizer binary in via GitHub, or is running that technically/contractually prohibited?

**Comment by bloodearnest** [comment]
So, I checked, and you mount //e/ paths from container with just the socket shared, you don't need to explicitly share /e/ with the job-runner container in order to use it for sub-docker commands. So @seb's comment is correct regards being in the context of the windows host.

However, `docker cp`, AFAICS, requires the source file be on the client-local filesystem, and can't magically directly access the host filesystem for the source file.

So, to be fast, I think we need to just run the `docker cp` part on the host, or find another way to copy data faster w/o going over the fileshare route.

**Comment by sebbacon** [comment]
This all sounds correct!

I don't think we are contractually or technically limited to not having python. It just seemed like a neater and simpler abstraction for managing python and cross-platform deploys. Oh the naivety.

This is probably the next best step.
