### ISSUE TITLE
Use PosixPath rather than Path for correct behaviour on Windows

### ISSUE THREAD

**Issue by wjchulme** [opensafely/job-runner#60]
For the [`os-demo-research/tree/cohort-study`](https://github.com/opensafely/os-demo-research/tree/45490f0ec96adfe97be8a296b4d2e1915d13ffe6) repo, I'm trying to test the [project.yaml](https://github.com/opensafely/os-demo-research/blob/45490f0ec96adfe97be8a296b4d2e1915d13ffe6/project.yaml) locally, as per instructions [here](https://docs.opensafely.org/en/latest/project_pipelines/)

When I try to run the first action using `cohortextractor run dummy generate_cohort_deaths expectations`, it gives the following error:

```
Invalid requested path \workspace\output\input_deaths.csv, not in /workspace
```

I suspect this is just a silly mistake somewhere but I can't get past it. Perhaps I'm specifying relative file paths wrong in the yaml but I've tried a few things with no success.

**Comment by evansd** [comment]
I suspect the problem there is using backslashes instead of forward slashes. We could probably add something to detect and warn about that. I think we want to enforce slashes to be consistent though.

**Comment by wjchulme** [comment]
The error gives `\` but in the yaml and elsewhere I'm always using `/`.

**Comment by evansd** [comment]
Ah! Then I bet I know what this is.

Note to self: make sure we use `PosixPath` explicity everywhere rather than `Path` otherwise it won't behave as expected on Windows.
