### ISSUE TITLE
[v2] Local Testing

### ISSUE THREAD

**Issue by ghickman** [opensafely/job-runner#80]
My branch, `job-server-compat`, has a failing test locally which is passing in CI.  `test_integration` gets both the wrong number of jobs and has the wrong statuses.

Here's the output from pytest:
```
        # Run sync to grab the JobRequest from the mocked job-server
        jobrunner.sync.sync()
        # Check that three pending jobs are created
        jobs = get_posted_jobs(requests_mock)
>       assert [job["status"] for job in jobs.values()] == [
            "pending",
            "pending",
            "pending",
            "pending",
        ]
E       AssertionError: assert ['failed'] == ['pending', '...g', 'pending']
E         At index 0 diff: 'failed' != 'pending'
E         Right contains 3 more items, first extra item: 'pending'
E         Full diff:
E         - ['pending', 'pending', 'pending', 'pending']
E         + ['failed']
```

This is mostly for me to dig back into later but if this is an obvious failure then please do point me in the right direction @evansd!

**Comment by sebbacon** [comment]
@ghickman is this still live?

**Comment by ghickman** [comment]
This is still happening for me on the `version-2` branch.  IIRC Dave isn't seeing this locally and it's not happening on GHA so I've not spent any time investigating yet.

**Comment by ghickman** [comment]
I've tracked this down to having `init.deafultBranch = main` in my global gitconfig, while the test JobRequest is configured with `"branch": "master"`.

**Comment by evansd** [comment]
Ah! Excellent sleuthing. I can fix the test to be robust against this.

**Comment by ghickman** [comment]
I'm just looking at it now, I think the easiest fix is to ensure the git repo has a master branch?

**Comment by ghickman** [comment]
Ok, don't run `git checkout -B master` in your working directory…

**Comment by evansd** [comment]
:grimacing: 

I think just changing `master ` to `HEAD` in the test setup will do the trick.

**Comment by ghickman** [comment]
That's a very good point, just a lot less fun!  PR incoming.
